"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import os, sys
from setuptools import setup
# from cx_Freeze import setup,Executable

# os.environ['TCL_LIBRARY'] = "./mylabelimage/Contents/lib/8.5"

APP = ['mylabelimage.py']
DATA_FILES = []
OPTIONS = {"packages":["numpy", "tensorflow", "cv2", "PIL", "pyscreenshot", "tkinter", "serial"], \
"resources":[os.getcwd() + "/output_labels.txt", os.getcwd() + "/output_graph.pb", os.getcwd() + "/serviceaccount.json"]}


setup(
    app=APP,		
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    install_requires=['firebase_admin', 'google-cloud-firestore']
)



# os.environ['TCL_LIBRARY'] = "C:\\Users\\woner\\AppData\\Local\\Programs\\Python\\Python36\\tcl\\tcl8.6"
# os.environ['TK_LIBRARY'] = "C:\\Users\\woner\\AppData\\Local\\Programs\\Python\\Python36\\tcl\\tk8.6"

# base = None

# build_exe_options = dict(


#         includes = ["numpy","tensorflow","cv2","pyscreenshot","tkinter", "threading", "PIL","firebase_admin"],

#         include_files = [os.getcwd() + "/output_graph.pb", os.getcwd() + "/output_labels.txt"]
# )

# setup(  name = "mylabel",
#         version = "0.1",
#         description = "My GUI application!",
#         options = {"build_exe": build_exe_options},
#         executables = [Executable("mylabelimage.py", base=base)])